export const interestOptions = [
    { label: 'Sports', icon: '⚽' },
    { label: 'Arts & Crafts', icon: '🎨' },
    { label: 'Music', icon: '🎵' },
    { label: 'Reading', icon: '📚' },
    { label: 'Dancing', icon: '💃' },
    { label: 'Science', icon: '🔬' },
    { label: 'Outdoor Activities', icon: '🏕️' },
    { label: 'Technology', icon: '💻' },
    { label: 'Cooking', icon: '🍳' },
    { label: 'Animals', icon: '🐶' },
    { label: 'Traveling', icon: '✈️' },
    { label: 'Board Games', icon: '🎲' },
    { label: 'Gardening', icon: '🌱' },
    { label: 'Photography', icon: '📸' },
    { label: 'Theater & Drama', icon: '🎭' },
    { label: 'Video Games', icon: '🎮' },
];

export const allergyOptions = [
    'Peanuts',
    'Tree Nuts',
    'Milk',
    'Eggs',
    'Wheat',
    'Soy',
    'Fish',
    'Shellfish',
    'Sesame',
    'Gluten',
    'Corn',
    'Mustard',
    'Celery',
    'Lupin',
    'Sulfites',
    'Latex',
    'None',
]
