INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Civic & Community Engagement Goals (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Mastered', 'Sense of Belonging',
 'Recognize being part of family, school, and community',
 'Identifies their family, school, or neighborhood in 3/4 discussions',
 'Talk about "our home," "our masjid," "our street," etc.',
 'Builds identity, safety, and pride',
 '6–8 guided discussions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Community Rules',
 'Follow simple rules: take turns, wait in line, clean up',
 'Completes 3/4 tasks following rules',
 'Practice at home: "We take turns," "We clean up together"',
 'Teaches social order and shared responsibility',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Helping Others',
 'Enjoy simple helping roles—pass a toy, hand out napkins, tidy up',
 'Performs helper tasks 3/4 times daily',
 'Assign a "helper of the day" job at home or school',
 'Builds kindness, cooperation, and responsibility',
 '6–8 times in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Celebrate Differences',
 'Appreciate different names, foods, languages, appearances',
 'Can identify 3/4 differences in stories or activities',
 'Read books about diverse families and traditions',
 'Encourages tolerance and cultural respect',
 '4–6 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Mastered', 'Kind Words & Actions',
 'Say "please," "thank you," "sorry," and greet others politely',
 'Uses polite phrases in 3/4 interactions',
 'Model and role-play polite interactions',
 'Builds social harmony and respectful behavior',
 '12–16 times in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Group Participation',
 'Enjoy singing, playing, praying, and working in groups',
 'Participates in 3/4 group activities',
 'Encourage teamwork in play or classroom activities',
 'Builds cooperation and confidence',
 '6–8 group sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Appreciate Local Helpers',
 'Recognize roles like teachers, doctors, imams, firefighters',
 'Identifies 3/4 helpers and expresses appreciation',
 'Point out helpers and say thank you together',
 'Sparks admiration and respect for public service',
 '4–6 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Respect Shared Spaces',
 'Throw trash in bin, take care of books and toys',
 'Completes 3/4 tasks properly',
 'Practice cleanup routines at home and in public',
 'Teaches stewardship and mindfulness',
 '6–8 routines in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Give Back in Small Ways',
 'Involve in acts of charity: pack food, give coins, donate clothes',
 'Participates in 2–3 acts of giving per month',
 'Create a monthly family "give day" with simple acts',
 'Builds a lifelong spirit of service',
 '1 "give day" per month', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Fairness',
 'Begin to grasp fairness and taking turns',
 'Takes turns fairly in 3/4 situations',
 'Use games to practice: "Now it''s your brother''s turn"',
 'Fosters justice, patience, and equity',
 '6–8 play sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Civic & Community Engagement Goals (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Community Awareness',
 'Understand what a community is',
 'Can describe 3–4 local places or groups',
 'Talk about neighbors, school, parks, and places of worship',
 'Builds identity, belonging, and social awareness',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Community Explorer badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Good Citizenship',
 'Practice kindness, respect, and helpfulness',
 'Performs 3–4 acts of kindness or respect per week',
 'Use stories or real-life examples of helpful people',
 'Promotes harmony, responsibility, and moral values',
 '3–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Kindness Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Volunteering & Clean-Up',
 'Participate in group clean-up or volunteering',
 'Joins at least one community activity',
 'Arrange park clean-ups, food drives, or garden projects',
 'Encourages social responsibility and cooperation',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Helping Hands badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'National Awareness',
 'Know national symbols and basic facts',
 'Can identify flag, anthem, and 2 major holidays',
 'Teach through songs, stories, and visual aids',
 'Builds national identity and civic knowledge',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Patriot Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Community Rules',
 'Follow community rules and laws',
 'Demonstrates understanding in 3–4 public situations',
 'Explain stop signs, quiet hours, and basic public rules',
 'Promotes order, safety, and accountability',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Rule Follower badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Public Space Respect',
 'Respect public spaces',
 'Avoids littering or damage in 3–4 outings',
 'Model behavior and practice cleanup routines',
 'Builds responsibility and mindfulness',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Space Steward sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Neighborly Behavior',
 'Learn to be a helpful neighbor',
 'Performs at least 2 small helpful acts per week',
 'Water plants, deliver small treats, greet neighbors kindly',
 'Encourages kindness, community engagement, and social connection',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Helpful Neighbor badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Respectful Communication',
 'Understand how to use voice respectfully',
 'Shares opinions politely in 2–3 group settings',
 'Model respectful speaking, practice in family or class discussions',
 'Builds communication, civic expression, and confidence',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Respectful Speaker sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Explore Helping Roles',
 'Learn about community helpers like firefighters, nurses',
 'Can name 3–4 community helpers and describe what they do',
 'Visit fire stations, read books about helpers',
 'Builds admiration for service and sense of purpose',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Helper Explorer badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Group Participation',
 'Join structured group activities (sports, scouts, clubs)',
 'Participates in at least 1–2 group events per month',
 'Encourage joining sports teams, scouts, or other clubs',
 'Builds teamwork, belonging, and social confidence',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Team Player sticker'),

-- Civic & Community Engagement Goals (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Citizenship & Civic Responsibility',
 'Understand the concept of citizenship and civic responsibility',
 'Can explain what it means to be a responsible citizen',
 'Discuss roles in society, voting rights, and how actions impact community',
 'Encourages awareness of role in society and positive contribution',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Responsible Citizen Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Local & National Government',
 'Learn about local and national government',
 'Can identify roles of government and basic civic duties',
 'Introduce government roles, voting, and importance of laws',
 'Provides foundation for understanding political systems and civic duties',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Government Explorer Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Volunteering & Helping Others',
 'Engage in volunteering and helping others',
 'Participates in at least one community service activity',
 'Volunteer as a family, help neighbors, or support local causes',
 'Fosters empathy and duty toward helping others',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Community Helper Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Social Issues & Diversity',
 'Develop understanding of social issues and diversity',
 'Can explain basic social issues and importance of inclusion',
 'Discuss different cultures, diversity, and fairness',
 'Promotes inclusivity and awareness of societal challenges',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Diversity Champion Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Environmental Responsibility',
 'Understand the value of recycling and environmental care',
 'Demonstrates eco-friendly habits at home or school',
 'Teach recycling, waste reduction, and conservation',
 'Encourages responsibility toward the planet',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Eco Hero Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Community Participation',
 'Learn about importance of voting and participating in community events',
 'Attends or discusses local events and understands civic role',
 'Discuss local elections, community meetings, and events',
 'Instills active participation in democracy',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Active Participant Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Social Manners & Etiquette',
 'Practice good manners and etiquette in social situations',
 'Can demonstrate polite greetings, thank-yous, and conversation',
 'Role-play public interactions and formal settings',
 'Builds respectful and positive community relationships',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Polite Citizen Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Charity & Giving Back',
 'Understand importance of giving back to the community (charity/Zakat)',
 'Participates in charity activity or family giving project',
 'Engage in charity events, fundraising, or donating used items',
 'Reinforces helping others and making a difference',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Generous Heart Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Community Belonging & Pride',
 'Foster a sense of belonging and pride in their community',
 'Expresses connection and participation in community events',
 'Attend fairs, festivals, or neighborhood activities',
 'Encourages connection and love for where they live',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Proud Neighbor Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'Working On', 'Conflict Resolution & Cooperation',
 'Learn conflict resolution and cooperation in group settings',
 'Can resolve disputes fairly and work effectively in groups',
 'Role-play disputes, practice sharing, and group project collaboration',
 'Promotes peace-building and teamwork skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Team Player Badge'),

-- Civic & Community Engagement Goals (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Understand Rights and Responsibilities as Citizens',
 'Builds awareness of their role in society',
 'Can explain basic civic rights, responsibilities, and the importance of voting',
 'Discuss basic civic rights, responsibilities, and the importance of voting',
 'Builds awareness of their role in society',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Informed Citizen Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Volunteer and Serve in the Community',
 'Cultivates empathy and social responsibility',
 'Participates in at least 2 community service activities',
 'Get involved in charity work, local clean-ups, helping elderly neighbors',
 'Cultivates empathy and social responsibility',
 'Monthly', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Community Service Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Understand Global Issues and Cultures',
 'Promotes global awareness and tolerance',
 'Can discuss 2–3 global issues or cultural differences',
 'Watch documentaries, follow global news, and discuss world events with them',
 'Promotes global awareness and tolerance',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Global Citizen Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Participate in Environmental Advocacy',
 'Fosters care for the planet and sustainable practices',
 'Participates in 2–3 environmental activities',
 'Take part in recycling programs, plant trees, or join local environmental groups',
 'Fosters care for the planet and sustainable practices',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Environmental Advocate Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Learn about Local and National Politics',
 'Prepares for informed decision-making',
 'Can explain basic political processes and current issues',
 'Follow local elections, attend town hall meetings, research candidates and policies',
 'Prepares for informed decision-making',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Political Awareness Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Develop Leadership Skills through Community Projects',
 'Builds initiative and organizational skills',
 'Takes on leadership role in at least one project',
 'Take on leadership roles in school clubs, youth organizations, or community projects',
 'Builds initiative and organizational skills',
 '6–12 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Young Leader Award'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Understand Social Justice and Equality Issues',
 'Encourages fairness, equity, and advocacy',
 'Can explain 2–3 social justice concepts',
 'Discuss human rights, support diversity, and engage in inclusive conversations',
 'Encourages fairness, equity, and advocacy',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Justice Advocate Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Advocate for Positive Change in Society',
 'Empowers teens to stand up for their beliefs',
 'Participates in or organizes one advocacy activity',
 'Start a petition, organize an event, or volunteer for a cause they care about',
 'Empowers teens to stand up for their beliefs',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Change Maker Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Practice Conflict Resolution and Mediation',
 'Strengthens peaceful communication skills',
 'Demonstrates conflict resolution in 2–3 scenarios',
 'Role-play scenarios where they mediate disagreements or solve community conflicts',
 'Strengthens peaceful communication skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Peace Builder Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440008', NULL, NULL, 'To Do', 'Create or Support Local Initiatives',
 'Instills a sense of belonging and active citizenship',
 'Initiates or supports at least one local project',
 'Start a project with friends (e.g., food drive, school club), or support existing local causes',
 'Instills a sense of belonging and active citizenship',
 '6–12 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Community Builder Award');