INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Creative Expression & Communication Skills (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Speaking in Full Sentences',
 'Form simple, complete thoughts aloud',
 'Uses full sentences in 3/5 daily conversations',
 'Practice daily conversations: "What did you eat for lunch?"',
 'Develops clarity and confidence',
 '12–16 conversations in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Listening & Turn-Taking',
 'Understand conversations involve listening and responding',
 'Listens and responds appropriately in 3/5 interactions',
 'Use turn-taking games and read-aloud question time',
 'Builds respect and communication skills',
 '8–12 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Asking & Answering Questions',
 'Ask "what," "why," "how" questions and answer simply',
 'Asks/answers 3/5 questions during story or daily routines',
 'Encourage: "Do you have a question about the story?"',
 'Sparks curiosity and comprehension',
 '8–12 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Vocabulary Expansion',
 'Use 1–2 new words weekly from books, routines, or emotions',
 'Correctly uses new words in 3/5 opportunities',
 'Introduce new words weekly, model usage',
 'Grows language and expression',
 '8–12 opportunities in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Retelling Stories or Events',
 'Share events or stories in own words',
 'Retells 3/5 stories/events with sequence',
 '"Tell me what happened at the park today!"',
 'Strengthens memory, sequencing, and confidence',
 '6–8 retellings in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Singing & Rhymes',
 'Sing nursery rhymes and recite with rhythm',
 'Performs 3/5 rhymes correctly with actions',
 'Sing daily and practice action songs',
 'Boosts memory, pronunciation, and joy',
 '8–10 songs in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Role-Play & Pretend',
 'Act out stories or jobs using imagination',
 'Completes 3/4 pretend scenarios',
 'Provide props and let them lead games',
 'Encourages empathy and story-building',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Creating & Describing Artwork',
 'Make something and describe it',
 'Talks about artwork in 3/5 instances',
 'Ask: "Can you tell me about your drawing?"',
 'Builds self-awareness and expressive ability',
 '6–8 artworks in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Expressing Emotions Creatively',
 'Show feelings through drawing, movement, or storytelling',
 'Expresses emotions creatively in 3/5 opportunities',
 '"Draw what makes you feel safe" or "act out a happy face"',
 'Helps emotional literacy and stress relief',
 '6–8 creative expressions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Gestures & Facial Expressions',
 'Match body language to spoken words',
 'Uses gestures/facial expressions in 3/5 communications',
 'Practice in mirror or with dolls',
 'Supports social and emotional understanding',
 '6–8 practice sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Communicating Needs & Feelings',
 'Use words instead of crying or hitting',
 'Expresses feelings verbally in 3/5 daily situations',
 'Model phrases like "I feel upset because…"',
 'Builds emotional intelligence and self-regulation',
 '6–8 situations in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Creative Expression & Communication Skills (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Storytelling',
 'Tell stories with clear beginning, middle, and end',
 'Can tell a 3-part story in 3–4 attempts',
 'Encourage daily storytelling, comic strips, or recounting events',
 'Builds narrative skills, sequencing, and communication',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Storyteller Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Artistic & Musical Expression',
 'Express ideas through art, music, or dance',
 'Completes 2–3 creative projects per week',
 'Provide open-ended art supplies, musical instruments, or dance time',
 'Encourages imagination, emotional release, and self-expression',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Creative Genius badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Public Speaking & Confidence',
 'Speak clearly and confidently in front of others',
 'Presents or reads aloud in 2–3 small settings',
 'Practice show-and-tell, read-aloud, or mini presentations',
 'Builds verbal confidence, clarity, and presentation skills',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Confident Speaker badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Active Listening',
 'Listen and respond respectfully',
 'Reflects or responds appropriately in 3–4 conversations',
 'Model listening, use phrases like "I hear you saying…"',
 'Teaches conversation skills, empathy, and social engagement',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Listener Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Nonverbal Communication',
 'Use facial expressions and gestures to communicate',
 'Demonstrates 3–4 expressive gestures correctly',
 'Act out emotions, play charades, or role-play',
 'Supports understanding, emotional expression, and full-body communication',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Expression Expert badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Original Creation',
 'Create original drawings, stories, or songs',
 'Completes 2–3 original works per week',
 'Offer prompts like "Draw a world where animals talk" or storytelling',
 'Sparks imagination, individuality, and creative thinking',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Innovator Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Critical Thinking in Conversation',
 'Ask and answer questions thoughtfully',
 'Answers or asks 3–4 open-ended questions in conversations',
 'Encourage questioning during meals, drives, or reading',
 'Encourages curiosity, reasoning, and active conversation',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Curiosity Explorer badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Writing Communication',
 'Use writing to express ideas clearly',
 'Writes 2–3 short letters, journals, or notes per week',
 'Encourage journaling, letters to family, or notes for friends',
 'Builds literacy, clarity, and expressive writing',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Writer Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Role-Play Dialogue',
 'Use dialogue effectively in role-play or storytelling',
 'Engages in 2–3 role-play sessions using dialogue',
 'Set up pretend play scenarios like "store," "school," or "rescue mission"',
 'Strengthens expressive depth, social imagination, and empathy',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Role-Play Hero badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Humor & Playfulness',
 'Develop a sense of humor and playful communication',
 'Shares jokes, riddles, or funny stories in 2–3 interactions',
 'Share jokes, riddles, or create silly stories together',
 'Fosters joy, relatability, social bonding, and communication skills',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Funny Communicator sticker'),

-- Creative Expression & Communication Skills (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Public Speaking & Storytelling',
 'Develop confidence in public speaking and storytelling',
 'Can present a story or share ideas in front of family or peers',
 'Encourage storytelling or presentations with props or visual aids',
 'Builds communication skills, self-assurance, and clarity',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Storyteller Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Artistic Expression',
 'Encourage artistic expression (drawing, painting, music, drama)',
 'Produces at least one artwork, performance, or musical piece',
 'Introduce different mediums and allow creative exploration',
 'Fosters creativity, problem-solving, and emotional expression',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Creative Artist Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Writing & Idea Development',
 'Practice writing essays, stories, or poems',
 'Completes a short story, essay, or poem',
 'Set aside creative writing time; guide structure and vocabulary use',
 'Enhances literacy, imagination, and self-expression',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Writer''s Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Role-Playing & Dramatic Play',
 'Engage in role-playing and dramatic activities',
 'Participates in at least one skit or scenario',
 'Organize role-play activities with different characters and situations',
 'Boosts creativity, empathy, and understanding of others'' perspectives',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Actor Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Vocabulary & Language Skills',
 'Enhance vocabulary and language through conversations',
 'Uses new words or sentence structures in daily conversations',
 'Have daily discussions about interests, ideas, and opinions',
 'Improves communication, language development, and expression',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Word Wizard Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Emotional Expression',
 'Learn to express emotions through art and words',
 'Can describe or depict feelings in art, writing, or speech',
 'Provide opportunities to share feelings creatively through multiple forms',
 'Supports emotional intelligence and self-awareness',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Emotion Explorer Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Listening & Responding Skills',
 'Develop listening and responding skills in conversations',
 'Demonstrates active listening and thoughtful responses',
 'Model respectful communication, take turns, and make eye contact',
 'Strengthens social interactions and communication effectiveness',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Active Listener Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Group Discussions & Debates',
 'Encourage participation in group discussions or debates',
 'Shares ideas and listens to peers during group activities',
 'Introduce debates on simple topics; teach importance of listening',
 'Builds collaboration, critical thinking, and problem-solving skills',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Debater Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Body Language Awareness',
 'Understand importance of body language in communication',
 'Uses gestures, facial expressions, and posture effectively',
 'Role-play scenarios emphasizing nonverbal cues',
 'Supports clear, confident, and effective communication',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Body Language Pro Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'Working On', 'Technology for Creative Expression',
 'Use technology for creative expression (digital art, videos)',
 'Creates a digital artwork, animation, or short video',
 'Introduce apps or tools for video creation, digital art, or animations',
 'Encourages creative exploration and modern digital skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Digital Creator Badge'),

-- Creative Expression & Communication Skills (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Develop Clear and Effective Communication',
 'Enhances relationships and success in future endeavors',
 'Can communicate ideas clearly in 3–4 different contexts',
 'Practice speaking in front of others, joining debate teams, or giving presentations',
 'Enhances relationships and success in future endeavors',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Effective Communicator Award'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Express Thoughts and Emotions through Writing',
 'Helps process feelings and develop literary skills',
 'Completes 2–3 written pieces expressing thoughts or emotions',
 'Start journaling, write essays, or create short stories or poetry',
 'Helps process feelings and develop literary skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Expressive Writer Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Master Public Speaking Skills',
 'Boosts confidence and persuasion abilities',
 'Delivers 2–3 successful presentations or speeches',
 'Take part in speeches, presentations, or talent shows; join Toastmasters for youth',
 'Boosts confidence and persuasion abilities',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Public Speaker Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Explore Artistic Forms of Expression (Art, Music, Drama)',
 'Encourages creativity and mental well-being',
 'Creates 2–3 artistic works or performances',
 'Try painting, learn an instrument, or join a drama club',
 'Encourages creativity and mental well-being',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Creative Explorer Award'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Develop Critical Listening Skills',
 'Strengthens empathy and understanding of others'' views',
 'Demonstrates active listening in 3–4 conversations',
 'Practice active listening during conversations, listen to various forms of media critically',
 'Strengthens empathy and understanding of others'' views',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Active Listener Certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Create Digital Content (Videos, Podcasts, Blogs)',
 'Prepares for modern communication tools',
 'Produces 1–2 digital content pieces',
 'Start a YouTube channel, podcast, or blog on a topic of interest, experiment with editing tools',
 'Prepares for modern communication tools',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Digital Creator Award'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Collaborate with Others in Creative Projects',
 'Builds teamwork, negotiation, and social skills',
 'Completes 1–2 collaborative creative projects',
 'Work on group art projects, participate in collaborative writing or multimedia projects',
 'Builds teamwork, negotiation, and social skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Team Collaborator Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Cultivate Visual Communication (Design, Photography, Videography)',
 'Develops a modern form of communication and creativity',
 'Creates 2–3 visual communication projects',
 'Experiment with graphic design, photography, or filmmaking on a project or hobby',
 'Develops a modern form of communication and creativity',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Visual Communicator Award'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Use Social Media for Positive Expression and Advocacy',
 'Harnesses the power of social platforms responsibly',
 'Creates 2–3 positive social media posts or campaigns',
 'Share positive messages, art, or volunteer work through Instagram, TikTok, or other platforms',
 'Harnesses the power of social platforms responsibly',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Positive Influencer Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440009', NULL, NULL, 'To Do', 'Explore Storytelling Across Different Media (Digital, Visual, Spoken)',
 'Enhances imagination and the ability to communicate ideas effectively',
 'Creates stories in 2–3 different media formats',
 'Write short films, create graphic novels, or produce audio stories to share with family or online',
 'Enhances imagination and the ability to communicate ideas effectively',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Multimedia Storyteller Award');