INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Digital & Media Literacy Goals (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Screen Time Limits',
 'Understand when it''s time to stop screen use',
 'Stops using device at timer cue in 4/5 instances',
 'Use timers, visual schedules, "one show only" rules',
 'Prevents overuse, supports better sleep and focus',
 '6–8 guided sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Co-Viewing',
 'Watch or play media only with an adult',
 'Engages with adult in 3/4 media sessions',
 'Sit together, ask questions, discuss content',
 'Builds connection and guides learning',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Recognizing Educational Content',
 'Prefer shows/games that teach letters, numbers, or values',
 'Chooses educational content in 3/4 instances',
 'Parent guidance, recommend quality apps/shows',
 'Makes screen time beneficial and skill-building',
 '6–8 selections in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Mastered', 'Basic Device Handling',
 'Use tablet safely with two hands; keep food/drinks away',
 'Handles device properly in 4/5 uses',
 'Practice routines, set clear device rules',
 'Teaches care, responsibility, and safe handling',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Real vs. Make-Believe',
 'Understand that what happens on screens is not always real',
 'Correctly identifies 3/4 pretend vs. real scenarios',
 'Discuss cartoons vs. real life, guided reflection',
 'Prevents confusion, fear, and encourages critical thinking',
 '6–8 discussions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Eye Health Habits',
 'Look away every 20 mins, avoid close screen viewing',
 'Follows eye break routines in 3/4 sessions',
 'Play "eye spy" away from screen, stretch breaks',
 'Protects eyesight and encourages healthy habits',
 '6–8 routines in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Kindness in Digital Play',
 'Speak nicely on video calls or voice tools',
 'Uses polite language in 3/4 digital interactions',
 'Model polite talk, role-play family video calls',
 'Builds digital etiquette and social respect',
 '6–8 guided sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Ask for Help Online',
 'Tell a parent if something strange/scary appears',
 'Reports unusual content in 3/4 instances',
 'Role-play scenarios, model appropriate responses',
 'Prepares for digital safety and builds trust',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Technology for Learning',
 'Use apps for drawing, stories, or music',
 'Completes 2/3 creative digital projects independently',
 'Explore apps together, guide step-by-step',
 'Encourages creativity, learning, and productive digital use',
 '3–4 projects in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Screens as Privilege',
 'Understand screen time is earned, not a right',
 'Limits screen use to earned sessions in 4/5 instances',
 'Link device time to responsibilities, praise adherence',
 'Supports discipline, appreciation, and responsibility',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Digital & Media Literacy Goals (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Screen Time Limits',
 'Understand and follow screen time limits',
 'Follows daily schedule in 4/5 days',
 'Create a visual tech schedule and reminders',
 'Builds balance, prevents overuse, supports sleep and focus',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Screen Smart badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Age-Appropriate Content',
 'Recognize and choose age-appropriate content',
 'Chooses suitable content in 4/5 interactions',
 'Pre-approve shows/apps, explain why some content is inappropriate',
 'Protects emotional and cognitive health',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Content Aware sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Permission & Boundaries',
 'Use devices only with permission',
 'Asks before using devices in 4/5 situations',
 'Teach asking before using devices and reinforce rules',
 'Builds accountability, respect, and digital boundaries',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Permission Pro badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Online Safety Basics',
 'Know the basics of online safety',
 'Can explain 2–3 safety rules (e.g., no sharing personal info)',
 'Discuss dangers, use simple rules: name, school, address',
 'Protects against harmful exposure',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Safety Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Breaks from Screens',
 'Practice taking regular breaks from screens',
 'Takes scheduled breaks in 3–4 of 5 daily opportunities',
 'Schedule tech-free hours with fun offline activities',
 'Supports physical health, creativity, and mental rest',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Break Time Champion badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Technology for Learning',
 'Use technology for learning',
 'Completes 2–3 educational activities per week',
 'Guide them to use apps, reading programs, or science videos',
 'Encourages curiosity, skill-building, and productive use',
 '3–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Digital Learner sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Ads vs. Content Awareness',
 'Begin to understand difference between ads and content',
 'Can identify ads vs. shows/games in 3/5 examples',
 'Explain ad purpose, point out differences, discuss how content informs',
 'Fosters early media literacy and critical thinking',
 '3–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Media Aware badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Device Care',
 'Handle devices carefully and respectfully',
 'Demonstrates care in 4/5 interactions',
 'Show cleaning, carrying, and storing properly',
 'Builds responsibility, respect, and prolongs device life',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Careful Techie sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Digital Boundaries',
 'Respect others'' digital boundaries',
 'Asks permission before taking photos/videos in 4/5 cases',
 'Teach consent rules and model respectful behavior',
 'Develops consent awareness and digital respect',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Respectful User badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Online Communication',
 'Talk about what they see online',
 'Discusses confusing or scary content in 3/5 instances',
 'Encourage open conversations and reflection',
 'Opens dialogue, provides guidance, and supports safe online habits',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Safe Communicator sticker'),

-- Digital & Media Literacy Goals (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Device Basics',
 'Understand the basics of digital devices and how they work',
 'Can use tablet, computer, or smartphone for simple tasks',
 'Teach responsible use: typing, searching, using apps',
 'Builds technological literacy and comfort with devices',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Tech Explorer Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Online Safety & Privacy',
 'Learn about online safety and privacy',
 'Identifies safe vs. unsafe online behaviors',
 'Discuss not sharing personal info, strong passwords, and safe websites',
 'Promotes safe digital habits and awareness of risks',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Safety Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Critical Media Thinking',
 'Develop critical thinking skills for media consumption',
 'Can evaluate sources and recognize reliable vs. unreliable info',
 'Teach to ask questions like: "Who made this? Is this trustworthy?"',
 'Encourages discernment in media consumption',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Media Detective Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Cyberbullying Awareness',
 'Understand the concept of cyberbullying and how to respond',
 'Explains what to do if they witness or experience cyberbullying',
 'Discuss handling, reporting, and supporting others',
 'Promotes respectful online behavior and awareness of risks',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Kind Clicker Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Digital Etiquette',
 'Practice digital etiquette (respecting others online)',
 'Demonstrates polite, kind communication online',
 'Teach kindness, avoiding trolling or spreading rumors',
 'Encourages kindness and respect in online spaces',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Polite Poster Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Search Skills',
 'Learn how to use search engines effectively',
 'Can find reliable info online independently',
 'Teach Google searches, evaluating sources',
 'Encourages responsible and efficient internet use',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Search Pro Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Screen Time Awareness',
 'Recognize the impact of screen time on health',
 'Follows agreed-upon screen time limits and takes breaks',
 'Set screen limits, encourage breaks and balance with physical activity',
 'Supports a balanced relationship with technology',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Balanced Tech Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Media Literacy',
 'Develop media literacy (ads, games, videos)',
 'Can explain how ads or games influence people',
 'Discuss advertising intent, entertainment vs. educational content',
 'Teaches critical thinking about media messages',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Media Minded Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Digital Footprint Awareness',
 'Understand digital footprint and online reputation',
 'Can explain why online actions matter long-term',
 'Discuss permanence of posts and sharing responsibly',
 'Encourages awareness of online actions affecting future opportunities',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Digital Citizen Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Positive Tech Use',
 'Explore positive ways to use technology (learning apps, creative tools)',
 'Uses apps or creative tools for learning or creating content',
 'Introduce educational apps, coding platforms, or video creation tools',
 'Fosters productive and creative use of technology',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Creative Coder Badge'),

-- Digital & Media Literacy Goals (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Understand Digital Footprint and Online Identity',
 'Builds awareness of long-term consequences',
 'Can explain what a digital footprint is and review own online presence',
 'Teach them to Google themselves, review privacy settings, discuss responsible posting',
 'Prepares for safe, responsible online presence',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Digital Awareness Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Use Social Media Responsibly',
 'Prevents harm to self and others',
 'Follows agreed-upon social media boundaries',
 'Set boundaries, discuss peer pressure, teach content discernment',
 'Reduces risk of online conflict and oversharing',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Responsible Poster Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Recognize Misinformation and Fake News',
 'Builds critical thinking and media awareness',
 'Can identify fake news or biased content',
 'Practice fact-checking, analyze sources, discuss clickbait and bias',
 'Develops analytical skills and critical media literacy',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Fact Checker Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Maintain Digital Etiquette and Communication',
 'Fosters respectful interactions',
 'Demonstrates polite and effective online communication',
 'Teach online manners, tone, and impact of words on others',
 'Encourages respectful and professional digital behavior',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Online Etiquette Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Balance Screen Time with Offline Life',
 'Supports mental and physical health',
 'Follows daily screen time limits',
 'Create tech-free zones/times, promote hobbies and real-life interactions',
 'Prevents digital burnout and encourages balance',
 '1–2 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Screen Balance Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Protect Personal Information and Privacy',
 'Guards against exploitation and danger',
 'Uses strong passwords, recognizes phishing attempts',
 'Teach about phishing, strong passwords, and how to respond to suspicious activity',
 'Ensures safety and security online',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Privacy Protector Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Understand Online Safety and Cyberbullying',
 'Helps respond wisely to threats',
 'Knows how to report cyberbullying and support peers',
 'Discuss reporting tools, emotional impacts, and strategies to help others',
 'Promotes safe and supportive online interactions',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Cyber Safety Champion'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Use Technology for Learning and Growth',
 'Encourages purposeful tech use',
 'Completes educational or creative digital tasks',
 'Introduce educational platforms, coding tools, and digital creativity apps',
 'Enhances learning, creativity, and skill development',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Digital Learner Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Respect Copyright and Digital Ownership',
 'Develops legal and ethical awareness',
 'Gives proper credit and avoids plagiarism',
 'Teach about plagiarism, fair use, citing sources, and image use',
 'Fosters ethical and responsible digital behavior',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Ethical User Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440007', NULL, NULL, 'Working On', 'Explore Digital Careers and Tools',
 'Prepares for future career opportunities',
 'Researches digital careers and completes mini-projects',
 'Explore fields like animation, programming, marketing; start small digital projects',
 'Builds career awareness and practical tech experience',
 '6–12 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Future Tech Star');