INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Emotional Developmental Goals (Ages 3–5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Emotion Recognition', 
'Recognize and name basic emotions (happy, sad, angry, scared)', 
'Identifies emotions in 4/5 scenarios', 
'Use emotion cards, mirror play, storybooks', 
'Builds self-awareness and emotional vocabulary', 
'4–5 times daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Emotional Expression', 
'Say “I feel sad/mad” instead of acting out', 
'Expresses feelings verbally in 3/5 daily situations', 
'Model phrases, use feelings chart', 
'Encourages healthy emotional expression', 
'3–5 times daily for 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Self-Regulation', 
'Use simple calming strategies (deep breathing, hugging a pillow)', 
'Uses strategy independently in 3/5 upsetting situations', 
'Practice routines, guided prompts', 
'Teaches self-control and reduces tantrums', 
'3–5 times per day for 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Impulse Control', 
'Wait their turn, resist hitting or grabbing', 
'Waits/responds appropriately in 3/5 situations', 
'Games like “Red Light, Green Light,” praise efforts', 
'Builds patience and respect for others', 
'3–5 attempts per session for 8 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Resilience', 
'Handle disappointment without full meltdown', 
'Demonstrates coping in 3/5 minor disappointments', 
'Role-play “it’s okay to feel upset” scenarios', 
'Builds frustration tolerance and adaptability', 
'3–5 times per week for 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Empathy', 
'Notice and respond to others’ feelings', 
'Responds empathetically in 3/5 situations', 
'Use dolls, role-play, or books to explore feelings', 
'Strengthens kindness and emotional intelligence', 
'3–5 times per week for 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Positive Self-Image', 
'Say “I can do it!” or “I’m good at drawing”', 
'Uses positive phrases in 3/5 daily interactions', 
'Praise effort, affirmation cards', 
'Encourages confidence and independence', 
'3–5 times daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Joy & Gratitude', 
'Share happy experiences and say thank you meaningfully', 
'Expresses gratitude in 3/5 situations', 
'Gratitude jars, daily prompts', 
'Reinforces emotional balance and optimism', 
'3–5 times daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Mastered', 'Identifying Triggers', 
'Recognize what makes them upset or overstimulated', 
'Identifies triggers in 3/5 scenarios', 
'Talk about day, drawings, reflection', 
'Helps avoid or prepare for challenging situations', 
'3–5 times per week for 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age3_5', '5 stars + certificate'),

-- Emotional Developmental Goals (Ages 6–8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Emotions', 
'Understand and name emotions', 
'Identifies 6–8 emotions and their causes in 3/5 daily check‑ins', 
'Use emotion charts/books; daily “How do you feel today?” check‑ins', 
'Builds emotional vocabulary and self‑awareness', 
'20–30 check‑ins in 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Frustration', 
'Manage frustration using healthy strategies', 
'Uses 2 coping strategies in 3/5 frustrating moments', 
'Teach deep breathing, count to 10, take a break; create a calm corner', 
'Reduces outbursts; builds resilience', 
'12–18 practice moments in 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Impulse', 
'Regulate impulses with “Stop–Think–Act”', 
'Pauses and chooses a plan in 3/5 tempting situations', 
'Role‑play scenarios; visual stop sign/reminder', 
'Improves self‑control in school and social settings', 
'12–16 practices in 8 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Awareness', 
'Recognize impact of emotions on behavior', 
'Explains feeling → action in 3/4 examples', 
'Discuss cause/effect (“When I’m angry, I yell; when calm, I use words”)', 
'Builds insight, empathy, and accountability', 
'8–12 discussions in 4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Compassion', 
'Show empathy and compassion toward others', 
'Offers kind words/help in 3/5 opportunities', 
'Model empathy; prompt noticing others’ feelings; gratitude/kindness prompts', 
'Strengthens relationships and prosocial behavior', 
'12–16 acts in 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Self‑Esteem', 
'Develop healthy self‑esteem through effort‑based praise', 
'Uses growth phrases (“I can try,” “I’ll keep practicing”) in 3/5 challenges', 
'Praise effort, not outcomes; avoid comparisons; keep a “strengths/brag” journal', 
'Boosts confidence and persistence', 
'15–20 reflections in 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Expression', 
'Express emotions verbally (“I feel … because …”)', 
'Uses an “I feel…” statement in 3/5 conflict situations', 
'Teach sentence stems; role‑play; feelings chart by the calm corner', 
'Replaces acting out with communication', 
'10–15 rehearsals in 4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Stress', 
'Manage stress/worry with calming routines', 
'Uses a chosen strategy within 2 minutes in 3/4 worry instances', 
'Teach stretching, belly breathing, talk‑throughs, bedtime calming routine', 
'Builds coping skills and resilience', 
'8–12 practices in 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Confidence', 
'Build self‑confidence through positive, supported new experiences', 
'Attempts 1 new/previously avoided task per week', 
'Scaffold tasks; break into steps; celebrate small wins', 
'Increases willingness to try and persevere', 
'4–6 new tasks in 6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Support', 
'Seek help when feeling overwhelmed', 
'Asks a trusted adult for help in 3/4 challenging situations', 
'Teach a “help script,” identify trusted adults; practice asking in low‑stakes scenarios', 
'Teaches self‑advocacy and problem‑solving', 
'6–8 opportunities in 4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age6_8', '5 stars + certificate'),

-- Emotional Developmental Goals (Ages 9–11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 
'Working On', 'Identify & Name Complex Emotions', 
'Recognize and name emotions like frustration, excitement, jealousy', 
'Identifies emotions correctly in 4–5 scenarios', 
'Discuss emotions daily, use emotion charts or situational examples', 
'Supports emotional vocabulary, self-awareness, and emotional literacy', 
'3–5 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Emotion Expert Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Emotional Regulation', 
'Practice managing anger, stress, and frustration', 
'Uses coping strategies in 3–5 challenging situations', 
'Teach deep breathing, counting, taking breaks, or guided relaxation', 
'Encourages resilience, patience, and self-control', 
'3–5 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Calm Star Sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Express Feelings Healthily', 
'Share feelings calmly and respectfully', 
'Expresses emotions verbally in 3–5 situations', 
'Role-play scenarios, model respectful expression, encourage dialogue', 
'Promotes mental well-being and effective communication', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Healthy Communicator Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Develop Empathy', 
'Understand and respond to others’ emotions', 
'Shows empathy in 3–5 peer or family interactions', 
'Discuss others’ feelings, model empathy, practice perspective-taking', 
'Fosters kindness, perspective-taking, and social responsibility', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Empathy Champion Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Impact of Actions on Others', 
'Reflect on how actions affect friends and family', 
'Demonstrates awareness in 3–5 situations', 
'Encourage reflection after conflicts, discuss consequences', 
'Encourages social responsibility, accountability, and kindness', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Responsibility Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Positive Self-Talk & Confidence', 
'Manage self-doubt and use affirmations', 
'Uses positive self-talk in 3–5 challenging moments', 
'Introduce affirmations, journaling, and guided reflection', 
'Builds self-confidence, resilience, and mental well-being', 
'3–5 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Confidence Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Peer & Social Pressure', 
'Respond positively to peer influence', 
'Makes independent choices in 3–5 scenarios', 
'Role-play peer pressure situations, discuss saying “no” kindly', 
'Fosters independence, assertiveness, and strong values', 
'3–5 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Independent Thinker Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Gratitude Practice', 
'Express gratitude daily', 
'Demonstrates gratitude in 3–5 instances per week', 
'Encourage journaling, family gratitude circles, or verbal sharing', 
'Promotes positivity, contentment, and mental well-being', 
'3–5 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Gratitude Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Friendship Navigation & Reconciliation', 
'Apologize, forgive, and rebuild trust in friendships', 
'Practices reconciliation successfully in 2–3 situations', 
'Role-play conflict resolution, guide apologies and forgiveness', 
'Teaches conflict resolution, emotional growth, and relational skills', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Friendship Builder Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Recognize & Address Anxiety or Fears', 
'Identify fears and practice coping strategies', 
'Uses coping strategies in 2–3 anxiety-provoking situations', 
'Discuss fears, teach relaxation techniques, model coping strategies', 
'Encourages self-awareness, stress management, and emotional resilience', 
'3–5 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age9_11', 'Bravery Star'),

-- Emotional Developmental Goals (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Build Emotional Self-Awareness', 
'Helps teens understand their feelings and triggers', 
'Tracks moods and identifies triggers for 4 weeks', 
'Encourage journaling, mood check-ins, or emotional vocabulary exercises', 
'Builds self-knowledge, empathy, and emotional intelligence', 
'4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Self-Aware Badge + personal reflection'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Develop Emotional Regulation and Coping Strategies', 
'Reduces impulsivity and supports mental health', 
'Demonstrates 3–5 coping strategies successfully', 
'Teach breathing exercises, mindfulness, or healthy outlets like sports or art', 
'Supports stress management, decision-making, and wellbeing', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Calm Mind Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Strengthen Self-Esteem and Confidence', 
'Builds resilience and a healthy sense of identity', 
'Completes 2–3 personal goals or challenges', 
'Praise effort over outcome, encourage setting and achieving personal goals', 
'Promotes confidence, motivation, and independence', 
'6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Confidence Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Learn to Manage Stress and Anxiety', 
'Promotes balance and reduces burnout', 
'Successfully uses stress management techniques for 2–3 weeks', 
'Discuss stressors, build calming routines, teach time management', 
'Reduces burnout and improves overall mental health', 
'3–4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Stress-Free Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Practice Empathy and Compassion', 
'Fosters healthy relationships and social harmony', 
'Participates in 2–3 volunteer or kind acts', 
'Volunteer together, discuss how others feel in stories or real-life events', 
'Builds social awareness, kindness, and relationship skills', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Empathy Award'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Accept and Learn from Failure', 
'Encourages growth mindset and perseverance', 
'Reflects on 2–3 past mistakes and identifies lessons', 
'Share your own failures, reframe mistakes as learning opportunities', 
'Develops resilience, adaptability, and maturity', 
'4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Resilience Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Develop Assertiveness and Say “No” Respectfully', 
'Protects boundaries and encourages healthy interactions', 
'Successfully practices assertiveness in 3–4 scenarios', 
'Role-play scenarios where they practice standing up for themselves kindly', 
'Promotes self-respect, boundary-setting, and confidence', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Assertiveness Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Understand Mental Health and Seek Help When Needed', 
'Normalizes emotions and reduces stigma', 
'Identifies situations requiring help and seeks support', 
'Talk about emotional wellbeing openly, know when to involve a counselor or therapist', 
'Encourages self-advocacy, awareness, and healthy coping', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Mental Health Awareness Certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Process and Express Complex Emotions', 
'Prevents emotional bottling and builds maturity', 
'Shares feelings verbally, through writing, or art 2–3 times a week', 
'Offer a safe space to vent, validate feelings without judgment', 
'Develops maturity, communication, and emotional balance', 
'4–6 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Emotional Expression Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440002', NULL, NULL, 'Working On', 'Practice Gratitude and Positive Thinking', 
'Improves emotional well-being and perspective', 
'Completes a daily gratitude practice for 4 weeks', 
'Keep a gratitude journal, name three good things daily, or reflect on positives after challenges', 
'Builds optimism, resilience, and mental wellness', 
'4 weeks', true, true, NOW(), NOW(), false, false, 0, 
'age_12plus', 'Gratitude Star Badge');