INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Faith/Religion Developmental Goals (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Mastered', 'Love',
 'Link Allah/God with kindness and creation (e.g., "Allah made the trees/sun.")',
 'States a faith-linked idea in 3/5 prompts',
 'Picture books, simple gratitude prayers, nature walks',
 'Builds spiritual belonging and awe',
 '20–30 mentions in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Duas',
 'Recite short daily duas (before eating, sleeping, entering/leaving home)',
 'Recites 2–3 target duas in 4/5 routine moments',
 'Recite together, use rhyme/songs, visual cue cards',
 'Establishes consistent faith habits',
 '60–90 routines in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Prayer',
 'Join/practice basic salah movements beside an adult',
 'Stands/prays alongside for 2/3 opportunities weekly',
 'Child-size prayer rug/clothing, gentle invitations, short durations',
 'Builds familiarity and reverence for prayer',
 '12–18 times in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Manners',
 'Use faith-linked manners: "Bismillah," "Alhamdulillah," "JazakAllahu Khayran"',
 'Uses phrases in 7/10 relevant interactions',
 'Model language, role-play at meals/hellos, praise attempts',
 'Connects actions to beliefs; nurtures respect and gratitude',
 '90–120 uses in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Stories',
 'Recall 2–3 key points from simple Prophet stories',
 'Retells 2 facts in 2/3 story sessions',
 'Read-alouds, picture seerah, puppets/props',
 'Teaches morals and builds love for role models',
 '8–12 sessions in 8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Identity',
 'Say faith-identity phrase confidently (e.g., "I''m a Muslim!")',
 'States identity or a practice with pride in 3/5 opportunities',
 'Identity crafts/badges, mirror affirmations',
 'Fosters positive faith-based self-image',
 '12–16 affirmations in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Quran',
 'Treat the Qur''an gently; recognize it as a holy book',
 'Carries/stores respectfully in 4/5 interactions',
 'Keep a clean/high place, child''s picture Qur''an, model handling',
 'Cultivates reverence for scripture',
 '12–20 care moments in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Nature',
 'Name everyday "signs" of Allah in creation (rain, trees, sun, animals)',
 'Mentions 2 signs in 3/5 nature outings',
 'Point-and-name on walks, "spot the sign" game',
 'Builds gratitude and reflection through the natural world',
 '6–10 outings in 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Mosque',
 'Show basic mosque etiquette (calm body, quiet voice, respect for space)',
 'Participates calmly for 10–15 minutes in 3/4 visits',
 'Very short visits, "quiet bag," preview expectations, praise',
 'Strengthens community belonging and reverence',
 '3–6 visits in 6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'To Do', 'Charity',
 'Do small acts of giving (sadaqah jar, sharing toys, packing food with family)',
 'Completes 1 act per week',
 'Family "give day," visible jar/box, child chooses item to give',
 'Builds compassion, generosity, and service mindset',
 '6–8 acts in 2 months', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Faith/Religion Developmental Goals (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Mastered', 'Daily Prayers',
 'Memorize and understand basic daily prayers (short surahs/duas)',
 'Recites correctly 3/5 times after salah',
 'Practice together after prayer, repeat in small chunks, use visual cues',
 'Builds spiritual habit, connection to Allah',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Prayer Star badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Salah Participation',
 'Participate in daily salah with guidance',
 'Stands and follows in 4/5 prayer sessions',
 'Stand beside parent, model calmness and joy, gentle reminders',
 'Introduces discipline, love for worship',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Mini Worshipper sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Understanding Allah',
 'Understand the concept of Allah and His attributes',
 'Explains 2–3 attributes like Ar-Rahman or Al-Hakeem in conversation',
 'Use stories, nature examples, and simple analogies',
 'Builds love, awe, and trust in the Creator',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Attribute Explorer badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Islamic Manners (Adab)',
 'Learn Islamic manners: salaam, right hand use, saying Bismillah before eating',
 'Demonstrates correct adab in 4/5 observed instances',
 'Model manners, role-play daily routines, provide gentle reminders',
 'Teaches respectful behavior in faith and daily life',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Adab Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Celebrations',
 'Celebrate Islamic events with meaning',
 'Participates in 2–3 event preparations or rituals',
 'Involve child in Eid prep, Ramadan routines, storytelling nights',
 'Connects joy and identity to religion',
 '6–10 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Festival Helper badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Prophets'' Stories',
 'Listen to and understand stories of the Prophets',
 'Retells main story points from 2–3 prophet stories',
 'Share simple engaging stories daily, use picture books or puppets',
 'Makes faith relatable and inspiring',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Story Listener sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Halal & Haram Awareness',
 'Understand basic halal and haram concepts',
 'Identifies halal/haram for 3–4 simple foods or actions',
 'Discuss foods/actions, explain reasoning in simple terms',
 'Introduces moral awareness and decision-making',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Halal Hero badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Gratitude (Alhamdulillah)',
 'Practice gratitude and saying Alhamdulillah',
 'Says Alhamdulillah in 4/5 relevant daily moments',
 'Model gratitude at meals/bedtime, gentle prompts',
 'Encourages a thankful heart',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Grateful Heart sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Qur''an & Sacred Respect',
 'Respect the Qur''an and sacred items',
 'Handles Qur''an/items gently in 4/5 observed times',
 'Demonstrate handling, create clean, special space for Qur''an',
 'Builds reverence for the Word of God',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Qur''an Respect badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Muslim Identity',
 'Start building identity as a young Muslim',
 'Uses affirmations: "I am a kind, strong Muslim who loves Allah" 3/5 times',
 'Reinforce with daily affirmations, storytelling, praise',
 'Encourages pride, belonging, and spiritual identity',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Young Muslim Star sticker'),

-- Faith/Religion Developmental Goals (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Understanding Religious Teachings',
 'Develop a deeper understanding of religious lessons',
 'Explains lessons from stories of prophets in 3–5 contexts',
 'Discuss key lessons and relate them to daily life',
 'Strengthens spiritual foundation and moral reasoning',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Faith Learner Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Prayers and Rituals',
 'Learn the importance of daily prayers and rituals',
 'Performs prayers or rituals with guidance 4–5 times per week',
 'Teach significance of salah, fasting, and other rituals',
 'Encourages discipline, mindfulness, and connection with Allah',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Prayer Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Charity (Zakat)',
 'Understand and practice giving to others',
 'Participates in 2–3 acts of charity per month',
 'Involve in charity projects or donations',
 'Fosters empathy, kindness, and social responsibility',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Giving Heart Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Reflect on Personal Faith',
 'Build personal connection and identity',
 'Shares thoughts on faith in 2–3 discussions per week',
 'Encourage discussions about faith and relationship with Allah',
 'Strengthens self-awareness, spiritual growth, and moral compass',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Reflection Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Islamic Figures',
 'Learn about important Islamic figures',
 'Recalls stories and qualities of 3–5 Prophets',
 'Share stories of Prophets Muhammad (SAW), Ibrahim, Yusuf, etc.',
 'Deepens cultural, historical, and religious knowledge',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Prophet Stories Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Moral Character via Faith',
 'Practice forgiveness, gratitude, honesty, kindness, and integrity',
 'Demonstrates 2–3 examples of good behavior per week',
 'Discuss examples from Prophet Muhammad (SAW) emphasizing character',
 'Connects faith with everyday actions and ethical development',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Character Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Gratitude (Shukr)',
 'Understand the importance of daily gratitude',
 'Says "Alhamdulillah" and reflects on blessings 3–5 times daily',
 'Encourage daily reflection at meals or bedtime',
 'Promotes appreciation, contentment, and positive mindset',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Gratitude Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Respect for Observances and Others'' Beliefs',
 'Learn tolerance and respect for all religions',
 'Shows respectful behavior in 2–3 diverse settings per week',
 'Teach respect for others'' religious practices, model inclusivity',
 'Encourages social harmony, empathy, and respect',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Respect Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Memorization and Application of Verses/Hadiths',
 'Reinforce good behavior through faith',
 'Recites 1–2 short verses/Hadiths per week and applies lesson',
 'Choose one Hadith a week and discuss real-life applications',
 'Strengthens memory, moral development, and spiritual awareness',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Wisdom Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Participating in Prayer',
 'Develop independence in prayer',
 'Leads or participates in family prayer 3–5 times per week',
 'Encourage reminders, standing at the front, and leading small groups',
 'Builds discipline, confidence, and mindfulness',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Prayer Leader Badge'),

-- Faith/Religion Developmental Goals (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Establish Regular Personal Worship (Salah, Du''a)',
 'Builds discipline and strengthens connection to Allah',
 'Prays consistently and tracks progress',
 'Encourage independent prayer, track consistency, reflect on its meaning',
 'Strengthens spirituality, focus, and discipline',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Worship Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Understand the Deeper Meanings of Belief (Aqidah)',
 'Grounds identity and answers spiritual questions',
 'Can explain core beliefs and concepts in simple terms',
 'Study Quranic stories, attend halaqas or youth Islamic classes',
 'Builds confidence in faith and clarity of purpose',
 '6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Faith Explorer Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Memorize and Reflect on Selected Surahs and Ayahs',
 'Strengthens spiritual memory and connection to Quran',
 'Can recite and explain chosen verses',
 'Choose meaningful verses to memorize and discuss their application',
 'Enhances connection to Quran and spiritual reflection',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Quran Memory Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Practice Good Character as a Reflection of Faith',
 'Links actions to spiritual growth',
 'Demonstrates traits like honesty, patience, and kindness',
 'Focus on traits like honesty, patience, kindness, and justice',
 'Builds integrity, empathy, and social respect',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Character Champion Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Understand Islamic History and Prophetic Life',
 'Builds pride in faith and role models',
 'Can describe key events or lessons from prophetic life',
 'Read seerah books, listen to Islamic podcasts, create family quizzes',
 'Provides role models and context for moral development',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Prophet''s Path Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Participate in Community Worship and Service',
 'Fosters a sense of belonging and responsibility',
 'Attends mosque events or volunteers regularly',
 'Attend Friday prayers, volunteer at the mosque or for charity drives',
 'Encourages community connection and empathy',
 'Monthly', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Community Helper Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Ask and Explore Difficult Questions About Faith',
 'Encourages sincerity and deeper conviction',
 'Can ask thoughtful questions and discuss them safely',
 'Provide a safe space for doubts, direct to scholars, use open discussions',
 'Supports mature understanding and genuine faith',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Curious Faith Seeker Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Observe Ramadan with Meaning and Maturity',
 'Builds spiritual resilience and self-control',
 'Completes fasts and engages in reflection and charity',
 'Encourage full fasts, reflections, and charity during the month',
 'Enhances discipline, empathy, and spiritual reflection',
 'Annual (Ramadan)', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Ramadan Resilience Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Contribute to Zakat or Sadaqah Meaningfully',
 'Teaches selflessness and social responsibility',
 'Gives consistently and thoughtfully to causes',
 'Donate part of allowance or earnings, involve them in choosing causes',
 'Builds empathy, social responsibility, and generosity',
 'Monthly/Quarterly', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Generous Giver Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440005', NULL, NULL, 'Working On', 'Live Faith Daily — Not Just Rituals',
 'Develops holistic, internalized Islam',
 'Applies Islamic values in daily life',
 'Apply Islamic values in choices, friendships, media, and ambitions',
 'Encourages integrity, consistency, and spiritual depth',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Daily Faith Champion Badge');