INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Financial Literacy Goals (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Mastered', 'Recognize Money',
 'Identify coins and bills by name, color, or size',
 'Correctly names 3/4 coins or bills in 4/5 practice sessions',
 'Play "coin sorting," use pretend cash registers',
 'Builds early awareness and familiarity',
 '10–12 activities in 3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Money Has Value',
 'Learn that money is exchanged for goods or services',
 'Completes a purchase transaction in 3/5 practice sessions',
 'Let them hand over money at a store with guidance',
 'Teaches basic economic cause and effect',
 '6–8 real-life purchases in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Saving',
 'Learn to put money in a piggy bank for later',
 'Deposits coins at least 2 times per week',
 'Use clear jars for saving, giving, and spending',
 'Builds patience and goal-setting',
 '8–10 deposits in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Earning Through Effort',
 'Begin to connect effort or tasks with earning (small chores)',
 'Completes task and receives reward in 3/5 attempts',
 'Offer small coins for age-appropriate chores like picking toys',
 'Encourages work ethic and independence',
 '6–8 tasks in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Spending Choices',
 'Understand that you can''t buy everything at once—choices must be made',
 'Makes a choice correctly in 3/5 scenarios',
 'Give limited coins and let them choose between two small items',
 'Develops self-control and decision-making',
 '6–8 play transactions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Mastered', 'Sharing & Charity',
 'Learn that money can be used to help others',
 'Contributes coins or play money in 2/3 opportunities',
 'Involve them in putting money in a charity box or donating a toy',
 'Builds empathy and generosity',
 '4–6 giving acts in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'No Money = No Buying',
 'Understand that buying requires money, not just wanting',
 'Recognizes need for money in 3/5 play sessions',
 'Role-play store games, reinforce rules like "We''re not buying that today"',
 'Reduces frustration and encourages gratitude',
 '6–8 sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Needs vs Wants',
 'Recognize basic needs (food, clothes) vs wants (toys, candy)',
 'Correctly classifies items in 3/5 scenarios',
 'Use picture books or mealtime conversations to discuss',
 'Builds thoughtful consumption habits',
 '6–8 activities in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Handling Money',
 'Learn to keep money safe and not tear it',
 'Keeps coins intact in 3/5 opportunities',
 'Provide a labeled pouch or wallet for pretend play',
 'Encourages responsibility',
 '6–8 practice sessions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Mastered', 'Gratitude for Money',
 'Appreciate the value of what''s already owned',
 'Shares thanks or demonstrates contentment in 3/5 daily moments',
 'Regularly talk about blessings, practice toy rotation',
 'Fosters contentment and prevents entitlement',
 '6–8 discussions in 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Financial Literacy Goals (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Money Concept',
 'Understand the concept of money and its uses',
 'Identifies coins/bills and explains simple uses in 3/5 situations',
 'Use real coins/bills in pretend play, shopping, or role-play',
 'Builds awareness of how money works',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Money Explorer badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Needs vs. Wants',
 'Differentiate between needs and wants',
 'Sorts 4/5 items correctly into needs/wants',
 'Sort pictures or items into categories; discuss reasoning',
 'Teaches prioritization, budgeting, and thoughtful consumption',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Smart Spender sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Saving Basics',
 'Learn basic saving concepts',
 'Adds coins to piggy bank/clear jar consistently for 3–5 sessions',
 'Use a piggy bank or clear jar to track savings',
 'Builds patience, goal-setting, and delayed gratification',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Savings Star badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Simple Allowance',
 'Start using a small allowance',
 'Makes 3–5 decisions on saving, spending, or giving per week',
 'Give a small weekly allowance with guidance',
 'Introduces money management and personal responsibility',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Allowance Achiever sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Spending Choices',
 'Make small spending choices',
 'Chooses items independently 3/5 times',
 'Let them buy a snack or toy with their own money',
 'Builds decision-making, ownership, and consequence awareness',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Decision Maker badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Earning Through Effort',
 'Understand earning through chores or effort',
 'Completes optional chores to earn 3–5 small rewards',
 'Tie chores to rewards to show effort leads to income',
 'Teaches work ethic, effort-reward connection',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Earning Explorer sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Charity Awareness',
 'Introduce the idea of charity (Zakat/Sadaqah)',
 'Gives part of allowance or items to charity 2–3 times per month',
 'Provide a charity box or family giving day',
 'Encourages compassion and Islamic responsibility',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Generous Giver badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Counting & Handling Money',
 'Learn to count and handle money',
 'Counts coins/makes simple change correctly in 3/5 scenarios',
 'Practice counting coins, making change, or role-playing store transactions',
 'Builds numeracy, practical skills, and confidence',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Money Master sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Money Source Awareness',
 'Talk about where money comes from',
 'Explains 2–3 ways families earn money in conversation',
 'Discuss jobs, work, and how parents provide for the family',
 'Builds economic understanding and connection to real-life finances',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Economic Explorer badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Goal-Oriented Saving',
 'Begin saving for a goal (toy/book)',
 'Adds consistently to savings tracker for chosen goal for 3–5 weeks',
 'Help choose goal, use visual tracker, celebrate progress',
 'Develops delayed gratification and goal-setting skills',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Goal Getter sticker'),

-- Financial Literacy Goals (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Understanding Money',
 'Understand the concept of money and its value',
 'Explains difference between coins and bills, and their use',
 'Use play money or real money to show how money is exchanged for goods/services',
 'Teaches basics of currency and role of money in daily life',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Money Smart Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Earning Money',
 'Learn about earning money through work',
 'Completes small chores or tasks to earn allowance',
 'Introduce small jobs like chores or helping around the house',
 'Encourages work ethic and understanding of earning value',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Earn & Learn Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Saving Goals',
 'Practice setting and achieving savings goals',
 'Saves for a set goal in a jar or bank account',
 'Create a savings jar or bank account and set clear goals',
 'Builds habit of saving for future needs or wants',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Savings Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Budgeting',
 'Learn basic budgeting (income vs. expenses)',
 'Allocates allowance into savings, spending, and sharing',
 'Use simple budgeting examples to divide money for different purposes',
 'Encourages money management and planning',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Budget Boss Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Giving / Charity',
 'Understand importance of giving (charity/Zakat)',
 'Participates in 1–2 charitable activities per month',
 'Involve them in giving to a cause or donating items',
 'Encourages kindness, empathy, and social responsibility',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Generous Heart Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Needs vs. Wants',
 'Discuss needs vs. wants',
 'Can distinguish between at least 3–5 items as need vs. want',
 'Make a list of items and discuss which are essential vs optional',
 'Helps differentiate between essential and optional spending',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Wise Choices Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Spending Awareness',
 'Track spending and reflect on choices',
 'Keeps a record of allowance or purchases for a week',
 'Encourage reflection on what was spent and why',
 'Teaches awareness of money habits and decision-making',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Spending Tracker Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Making Purchases',
 'Learn to make simple purchases',
 'Completes at least 2–3 small purchases independently',
 'Let them practice buying small items, handling money, and receiving change',
 'Builds confidence in managing money',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Smart Shopper Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Concept of Interest',
 'Introduce the concept of savings growth/interest',
 'Observes savings increase over time',
 'Use a savings jar and explain how money grows when added over time',
 'Encourages understanding of money growth and delayed gratification',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Interest Learner Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Financial Responsibility',
 'Understand the importance of financial responsibility',
 'Explains why it''s important to live within means',
 'Discuss consequences of spending beyond allowance or simple debts',
 'Fosters good habits and responsible decision-making',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Responsible Money Badge'),

-- Financial Literacy Goals (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Understand the Value of Money',
 'Builds appreciation for earning, saving, and spending wisely',
 'Can explain how money is earned, spent, and saved',
 'Discuss family expenses, budgets, costs of wants vs. needs; use real-life examples',
 'Establishes foundational financial literacy and prudence',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Money Mindset Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Begin Earning Through Age-Appropriate Work',
 'Builds work ethic and independence',
 'Completes small jobs or micro-business tasks',
 'Help find small jobs (babysitting, pet care, tutoring) or start micro-businesses',
 'Teaches work ethic and value of effort',
 'Monthly', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Earn & Learn Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Create and Manage a Personal Budget',
 'Encourages responsibility and planning',
 'Tracks income, expenses, and savings',
 'Give monthly allowance; guide in planning and tracking spending',
 'Develops practical money management skills',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Budget Boss Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Learn to Save for Short- and Long-Term Goals',
 'Teaches patience, discipline, and financial planning',
 'Achieves savings targets for planned goals',
 'Set goals for gadgets, trips, or future education; track progress visually',
 'Builds delayed gratification and planning skills',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Goal Getter Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Understand the Difference Between Needs and Wants',
 'Prevents impulsive spending and fosters contentment',
 'Can differentiate needs vs. wants in decision-making',
 'Play budgeting games or "spend or save" challenges',
 'Encourages mindful spending and financial prioritization',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Smart Spender Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Use Banking Tools (Accounts, Apps)',
 'Prepares for modern financial systems',
 'Can navigate a youth bank account or app',
 'Open a youth savings account; explore simple finance apps',
 'Builds tech-savvy financial literacy',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Digital Finance Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Learn About Giving (Zakat, Charity)',
 'Encourages compassion and spiritual responsibility',
 'Contributes regularly to charity or family giving',
 'Allocate part of earnings for charity or support a cause',
 'Reinforces ethical and moral responsibility',
 'Monthly', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Generous Giver Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Understand Debt, Loans, and Interest',
 'Prepares for real-world financial risks',
 'Can explain borrowing, debt, and interest in simple terms',
 'Discuss credit cards, student loans, and borrowing wisely',
 'Builds awareness of financial consequences',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Smart Borrower Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Explore the Concept of Halal Earnings',
 'Links income to values and faith',
 'Chooses ethical/halal ways to earn',
 'Discuss halal income, ethical jobs, and Islam''s financial teachings',
 'Connects faith to financial decisions',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Ethical Earner Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440006', NULL, NULL, 'Working On', 'Plan for Future Financial Goals',
 'Encourages forward thinking and long-term planning',
 'Sets goals for university, business, or investments',
 'Discuss saving for higher education, business ideas, or introduction to investment basics',
 'Prepares for independence and financial foresight',
 '6–12 months', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Future Planner Star');