INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Life Skills + Critical Thinking & Problem Solving (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Routines',
 'Follow simple daily routines (e.g., brushing teeth, bedtime)',
 'Completes 3/5 routine steps independently',
 'Use visual charts, songs, step-by-step guidance',
 'Builds structure, predictability, and independence',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Self-Care',
 'Dress themselves (buttons, zippers, shoes)',
 'Dresses independently in 3/5 opportunities',
 'Provide guidance, practice, praise effort',
 'Builds fine motor skills and confidence',
 'Daily for 4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Chores & Responsibility',
 'Help with simple chores (water plants, set table, tidy toys)',
 'Completes assigned task 3/5 times',
 'Assign small, achievable tasks',
 'Builds work ethic, teamwork, and pride',
 '3–5 times per week for 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Problem Solving',
 'Solve simple problems (choose between options, fix block towers)',
 'Attempts solution independently in 3/5 situations',
 'Ask guiding questions, model thinking steps',
 'Builds confidence, decision-making, and reasoning',
 '3–5 times per week for 6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Choice-Making',
 'Make choices between two options (snacks, clothes, activities)',
 'Makes independent choices in 4/5 opportunities',
 'Offer limited choices, praise attempts',
 'Builds autonomy, confidence, and critical thinking',
 'Daily for 3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Safety Awareness',
 'Follow basic safety rules at home and outside',
 'Observes safety rules in 4/5 situations',
 'Practice through role-play and reminders',
 'Prevents injury and builds responsibility',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Asking for Help',
 'Recognize when they need assistance and ask for help',
 'Asks for help in 3/5 opportunities',
 'Model asking for help, reinforce positively',
 'Teaches self-advocacy and humility',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Hygiene & Health',
 'Wash hands, brush teeth, comb hair, bathe with help',
 'Completes hygiene routine 4/5 times',
 'Guide and supervise, use songs and games to reinforce habits',
 'Builds self-care, cleanliness, and body awareness',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Trying New Tasks',
 'Explore tasks like peeling a banana or folding a towel',
 'Completes 3/5 attempts independently',
 'Break tasks into small steps, model, praise effort',
 'Builds resilience, curiosity, and independence',
 '3–5 attempts per week for 6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Observation & Inquiry',
 'Notice details, ask questions, and explore materials',
 'Asks questions or notices details in 3/5 activities',
 'Nature walks, sensory bins, guided discussions',
 'Enhances curiosity, learning readiness, and problem-solving skills',
 '3–5 times per week for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Cause & Effect Understanding',
 'Predict outcomes of simple actions (e.g., water + plant = growth)',
 'Correctly predicts 3/5 scenarios',
 'Experiments with water, sand, blocks, and simple science activities',
 'Builds early scientific thinking and reasoning',
 '2–3 times per week for 4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Mastered', 'Creativity & Expression',
 'Use art, music, or imaginative play to express ideas',
 'Creates or role-plays in 3/5 activities',
 'Open-ended art materials, music, dress-up, role-play',
 'Encourages self-expression, innovation, and problem-solving',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Life Skills + Critical Thinking & Problem Solving (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Belongings',
 'Put toys/books in their designated place after play',
 'Puts away belongings in 4/5 after-play observations',
 'Give labelled bins/shelves; make quick clean-up songs; model the routine',
 'Builds ownership, order, and responsibility',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Routines',
 'Complete morning & bedtime checklists independently',
 'Completes checklist without prompting 5/7 days for 2 consecutive weeks',
 'Create visual checklist; practise together; use gentle reminders',
 'Creates structure, reduces parental prompts, builds confidence',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Decisions',
 'Make simple choices and explain likely consequence',
 'Chooses between 2 options and explains reason in 4/5 trials',
 'Offer limited choices daily; ask "why?" and praise reasoning',
 'Develops judgment, responsibility, and reasoning skills',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'ProblemSolve',
 'Propose a solution for everyday problems (broken toy, lost item) before asking',
 'Suggests ≥1 solution before asking for help in 4/5 incidents',
 'Brainstorm together, model steps, prompt with "what could we try first?"',
 'Builds resilience, creative thinking, and independence',
 '2–3 months', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Chores',
 'Learn basic household tasks (fold a small towel, sweep a small area)',
 'Completes task with ≤1 prompt in 4/5 opportunities',
 'Teach one step at a time, demonstrate, scaffold then fade help',
 'Encourages helpfulness, self-sufficiency, life readiness',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Money',
 'Use money for simple transactions or play-store purchases',
 'Handles simple transaction or play purchase correctly in 3/5 practice runs',
 'Practice with play store/allowance, count coins together',
 'Introduces budgeting, decision-making and basic numeracy',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Planning',
 'Plan simple tasks (make a packing list and pack for short trips)',
 'Prepares checklist and packs with minimal support in 4/5 trips',
 'Make lists together, use visuals, let child lead packing',
 'Develops organization, foresight and executive skills',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Persistence',
 'Work toward a multi-step goal (complete a puzzle, save for a toy)',
 'Shows steady progress on goal across 4/5 tracked sessions',
 'Create goal chart, break task into small steps, celebrate mini-wins',
 'Builds perseverance, motivation and follow-through',
 '3–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Help-Seeking',
 'Ask for help when stuck using clear language',
 'Asks "I need help with..." in 3/4 real tasks when stuck',
 'Teach and role-play help scripts; identify trusted adults',
 'Promotes self-advocacy, reduces frustration, speeds learning',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Safety',
 'Recall and follow basic safety rules (street, strangers, home)',
 'Applies safety rules correctly in 4/5 observed situations',
 'Role-play safety scenarios, rehearse steps, use consistent rules',
 'Prepares child for independent situations and reduces risk',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', '5 stars + certificate'),

-- Life Skills + Critical Thinking & Problem Solving (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Problem-Solving & Critical Thinking',
 'Think through problems and explore solutions',
 'Offers 2–3 possible solutions to a problem in 3–5 situations',
 'Encourage discussion: "What could you do differently?"',
 'Strengthens decision-making, creativity, and analytical thinking',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Problem-Solver Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Cause & Effect Understanding',
 'Recognize how actions lead to outcomes',
 'Identifies consequences in 3–5 examples',
 'Use stories or real-life situations: "What happens if you forget homework?"',
 'Develops logical thinking and awareness of consequences',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Logic Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Responsibility for Daily Tasks & Chores',
 'Complete assigned tasks independently',
 'Finishes 3–5 chores per week on time',
 'Create a weekly chore chart with achievable tasks',
 'Builds responsibility, independence, and life skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Chore Champion Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Budgeting & Saving Money',
 'Save and spend money wisely',
 'Demonstrates saving in 2–3 scenarios and tracks spending',
 'Introduce piggy bank, set goals for saving vs. spending',
 'Fosters financial literacy, planning, and delayed gratification',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Money Manager Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Basic Cooking Skills',
 'Prepare simple meals safely and independently',
 'Completes 2–3 simple recipes with supervision',
 'Guide in meal prep: making sandwiches, mixing ingredients, chopping safely',
 'Promotes independence, nutrition awareness, and self-sufficiency',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Junior Chef Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Time Management for School & Play',
 'Balance study and free time effectively',
 'Completes tasks within set times in 3–5 activities',
 'Use timers, schedules, or checklists for tasks and free time',
 'Encourages balance, efficiency, and self-discipline',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Time Master Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Healthy Eating Habits',
 'Make nutritious food choices',
 'Chooses healthy options in 3–5 meals',
 'Plan meals together, educate on portion sizes, model good nutrition',
 'Supports physical health, growth, and lifelong wellness habits',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Healthy Eater Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Delayed Gratification',
 'Wait for a desired reward instead of instant gratification',
 'Waits for a reward or saves money/items in 3–5 attempts',
 'Practice saving for a goal or delaying treats',
 'Builds patience, self-control, and long-term planning skills',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Patience Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Teamwork & Collaboration',
 'Work effectively with peers in group activities',
 'Participates and contributes positively in 3–5 group tasks',
 'Play team sports, board games, or collaborative projects',
 'Encourages cooperation, communication, and conflict resolution',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Team Player Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Navigating Setbacks & Failures',
 'Handle mistakes and challenges constructively',
 'Demonstrates learning from mistakes in 2–3 situations',
 'Encourage a growth mindset, praise effort, discuss lessons learned',
 'Builds resilience, perseverance, and problem-solving skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Resilience Star'),

-- Life Skills + Critical Thinking & Problem Solving (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Manage Personal Schedule and Commitments',
 'Prepares for adult responsibilities and time efficiency',
 'Creates and follows a weekly schedule consistently',
 'Use planners or digital calendars, manage school, work, and social balance',
 'Builds organization, reliability, and readiness for adult life',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Time-Management Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Cook Basic and Healthy Meals',
 'Promotes health and self-sufficiency',
 'Successfully prepares 2–3 simple meals independently',
 'Plan meals, follow simple recipes, learn to budget for groceries',
 'Encourages independence, nutrition, and responsibility',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Chef Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Do Laundry and Maintain Personal Hygiene',
 'Builds independence and self-respect',
 'Completes laundry and hygiene routines independently',
 'Teach washing/drying, separating clothes, and hygiene routines',
 'Promotes self-care, personal responsibility, and confidence',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Hygiene Hero Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Budget and Manage Money for Small Expenses',
 'Lays the foundation for financial independence',
 'Tracks spending and stays within allowance limits',
 'Give a monthly allowance and track spending with simple tools',
 'Builds money management skills and decision-making',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Money Management Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Make Informed Decisions and Evaluate Consequences',
 'Sharpens judgment and responsibility',
 'Reflects on past decisions and predicts outcomes in scenarios',
 'Use "if-then" thinking, reflect on past decisions, role-play problem-solving',
 'Supports critical thinking, accountability, and planning',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Wise Decision Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Solve Real-Life Problems Creatively',
 'Encourages innovation and resilience',
 'Completes 2–3 challenges using creative solutions',
 'Brainstorm solutions to family or school challenges; play strategy games',
 'Fosters problem-solving, creativity, and adaptability',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Problem-Solver Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Understand Basic Home and Self-Maintenance',
 'Encourages readiness for adult life',
 'Performs minor household tasks independently',
 'Learn to fix minor things, organize spaces, and care for belongings',
 'Builds independence, responsibility, and life skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Home Skills Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Develop Conflict Resolution Skills',
 'Fosters maturity in peer and family relationships',
 'Successfully mediates or resolves 2–3 conflicts',
 'Discuss disagreements calmly, practice listening and compromise',
 'Promotes emotional intelligence, social skills, and maturity',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Peacemaker Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Practice Safe and Responsible Use of Public Spaces',
 'Teaches safety and independence',
 'Demonstrates safe navigation in public settings',
 'Navigate transportation, understand rules and boundaries in shared spaces',
 'Encourages safety, responsibility, and independence',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Safety Star Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440003', NULL, NULL, 'Working On', 'Prepare for Part-Time Jobs or Volunteering',
 'Builds work ethic and real-world exposure',
 'Completes a résumé or participates in 1–2 interview simulations',
 'Help build a résumé, role-play interviews, or connect with local opportunities',
 'Supports career readiness, work ethic, and community engagement',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Work Experience Badge');