INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES

-- Physical Development & Health (Ages 3-5)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Gross Motor Skills',
 'Run, jump, hop, climb, balance on one foot',
 'Completes 4/5 activities successfully',
 'Practice through obstacle courses, dance, playground visits',
 'Builds strength, coordination, and confidence',
 'Daily for 4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Fine Motor Skills',
 'Hold crayons, cut with child scissors, stack blocks, simple puzzles',
 'Completes 4/5 fine motor activities',
 'Playdough, coloring, threading beads, block towers',
 'Prepares for writing, self-care, and daily tasks',
 'Daily for 4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Daily Physical Activity',
 'Engage in at least 60 minutes of active play daily',
 'Participates in active play 5/7 days per week',
 'Dance breaks, outdoor walks, bike/scooter time',
 'Supports healthy growth, emotional regulation, and energy',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Sleep Routine',
 'Sleep 10–13 hours (including naps) with consistent bedtime routine',
 'Follows bedtime routine 5/7 nights per week',
 'Establish calming pre-bed routine (bath, books, dua)',
 'Crucial for brain development and behavior',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Nutrition Awareness',
 'Try new foods, understand "grow foods" vs. "treats," eat with family',
 'Tastes new food 3/5 times per week',
 'Involve child in meal prep, read food-themed stories',
 'Supports lifelong healthy eating habits',
 '3–5 times per week for 6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Toileting Independence',
 'Use the toilet with minimal assistance and understand handwashing',
 'Completes 4/5 toileting routines independently',
 'Gentle reminders, child toilet seats, praise progress',
 'Promotes self-care, body awareness, and hygiene',
 'Daily for 4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Hydration Habits',
 'Recognize thirst and drink water throughout the day',
 'Drinks water 4/5 times per day',
 'Give own labeled water bottle, make water fun with fruit slices',
 'Vital for energy, digestion, and focus',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Body Awareness & Consent',
 'Know body parts, learn private parts'' names, understand "my body is mine"',
 'Correctly identifies body parts and says "no" confidently in 3/5 situations',
 'Teach correct names, role-play saying "No" confidently',
 'Builds body autonomy, safety, and protection against abuse',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Personal Hygiene',
 'Wash hands, brush teeth, comb hair, bathe with help',
 'Completes 3/5 hygiene routines independently',
 'Make routines playful: "brush the sugar bugs away!"',
 'Encourages cleanliness and self-respect',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Mastered', 'Safety Awareness',
 'Follow basic rules: don''t run into the street, hold adult hand, ask before touching',
 'Demonstrates safety behaviors in 3/5 relevant situations',
 'Model, role-play, visual cues',
 'Prevents injury and builds responsibility',
 'Daily for 4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age3_5', '5 stars + certificate'),

-- Physical Development & Health (Ages 6-8)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Coordination',
 'Develop coordination through play & sports (bike, jump-rope, ball skills)',
 'Performs target activity with success in 4/5 sessions (e.g., 10 jump-rope skips or 50 m bike ride or catches 3/5 attempts)',
 'Regular play sessions (3×/week), short skill drills, encouragement, helmet/proper gear',
 'Builds strength, balance, confidence, and gross motor skill',
 '8–12 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Active Star + 5 stars'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Hygiene',
 'Establish regular hygiene: brush teeth twice, bathe, wash hands, keep nails clean',
 'Brushes twice daily 6/7 days; washes hands before meals in 4/5 instances',
 'Visual routine chart, timers, supervised practice, praise for consistency',
 'Prevents illness, builds independence and self-care skills',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Hygiene Hero badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Nutrition',
 'Understand healthy foods and help prep simple snacks',
 'Identifies food groups in 4/5 examples; helps prep a healthy snack 2×/week',
 'Cook-together activities, food-group games, tasting & sorting activities',
 'Supports energy, growth, concentration, and healthy habits',
 '6–12 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Healthy Chef sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Activity',
 'Stay active daily (play, sport, or structured activity)',
 'Achieves ≥45–60 min active play on 5/7 days',
 'Schedule daily active breaks, family walks, sports/play dates',
 'Builds fitness, motor skills, mood regulation, and focus',
 '4–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Active Week trophy'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Body Awareness',
 'Know basic body parts, safe movement, and how to avoid danger',
 'Correctly names 6–8 body parts and demonstrates 3 safety moves in role-play',
 'Body-part songs, obstacle courses, safe-movement practice',
 'Prevents injury, builds confidence and body knowledge',
 '3–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Safety Star + 5 stars'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Sleep/Routine',
 'Follow a calm bedtime routine and sleep 9–11 hours',
 'Bedtime routine followed 5/7 nights; sleeps recommended hours',
 'Consistent bedtime, wind-down activities (books, no screens 30m), sleep chart',
 'Supports brain development, mood, learning, and behavior',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Good Sleep badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Self-Advocacy',
 'Recognize & say physical needs (tired, cold, hungry, hurt)',
 'Expresses physical need in words in 4/5 relevant situations',
 'Model phrases ("I''m tired" / "My tummy hurts"); role-play reporting needs',
 'Encourages safety, comfort, and timely care',
 '3–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Brave Speaker sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Dressing',
 'Choose weather-appropriate clothes and dress with minimal help',
 'Picks suitable outfits for weather 4/5 mornings',
 'Teach simple weather checks, offer 2-3 choices, practice outfit planning',
 'Builds independence and practical decision-making',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Weather Wise badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Hydration',
 'Drink water regularly and recognize thirst',
 'Drinks water (or refills bottle) 4–6 times/day in 5/7 days',
 'Provide labeled water bottle, set drinking reminders, make water fun (slices)',
 'Keeps organs working, improves focus, digestion, and energy',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'Hydration Hero sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'First Aid Basics',
 'Know basic first-aid responses for small cuts, nosebleeds & when to adult-help',
 'Demonstrates steps in role-play (apply pressure, raise hand, tell adult) in 3/4 sessions',
 'Teach simple steps, practice with role-play and first-aid kit, praise calmness',
 'Builds safety awareness, confidence and appropriate help-seeking',
 '6–8 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age6_8', 'First Aid Learner badge'),

-- Physical Development & Health (Ages 9-11)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Regular Physical Activity',
 'Engage in daily exercise through sports, swimming, or walking',
 'Participates in 4–5 sessions per week',
 'Make exercise fun, try different activities, join clubs or classes',
 'Encourages lifelong fitness habits, builds strength, coordination, and endurance',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Active Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Balanced Nutrition',
 'Eat a variety of healthy foods, understand food groups',
 'Chooses balanced meals in 3–5 meals per week',
 'Plan meals together, involve child in cooking, discuss nutrition',
 'Supports growth, energy, focus, and long-term well-being',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Healthy Eater Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Personal Hygiene',
 'Brush teeth, wash hands, and maintain cleanliness consistently',
 'Completes hygiene routine independently 4–5 times per week',
 'Use checklists, timers, or reward charts to make hygiene routines fun',
 'Prevents illness, encourages self-care and independence',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Hygiene Hero Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Good Sleep Habits',
 'Follow consistent bedtime routines and get sufficient rest',
 'Sleeps 9–11 hours per night consistently',
 'Set bedtime, bedtime routines, calm pre-sleep activities',
 'Supports physical growth, brain development, and emotional regulation',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Sleep Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Emotional Triggers for Physical Health',
 'Recognize how stress and emotions affect physical well-being',
 'Identifies triggers and uses 2–3 coping strategies per week',
 'Discuss mind-body connection, teach deep breathing or relaxation',
 'Encourages holistic health, stress management, and self-awareness',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Mind-Body Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Basic First Aid and Safety',
 'Learn to treat minor injuries and follow safety rules',
 'Demonstrates 2–3 first aid skills safely',
 'Teach bandaging, cleaning wounds, and safety rules at home and outdoors',
 'Builds independence, safety awareness, and preparedness',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Safety Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Awareness of Alcohol, Drugs, and Smoking',
 'Understand dangers and practice refusal skills',
 'Can explain risks and demonstrate refusal strategies',
 'Age-appropriate conversations, role-play peer pressure scenarios',
 'Prevents harmful behaviors and promotes healthy decision-making',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Smart Choices Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Active Play and Outdoor Exploration',
 'Spend time outside exploring, playing, and being active',
 'Participates in outdoor activity 3–5 times per week',
 'Set aside time for outdoor games, nature walks, or playground visits',
 'Enhances fitness, creativity, exploration, and emotional well-being',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Nature Explorer Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Listening to Body''s Needs',
 'Recognize hunger, tiredness, pain, or other physical cues',
 'Verbalizes needs in 3–5 situations',
 'Encourage checking in with their body, allow rest or nourishment as needed',
 'Promotes self-awareness, healthy habits, and prevention of burnout',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Body Smart Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Safe Use of Technology',
 'Balance screen time with physical activity and offline hobbies',
 'Follows tech limits in 4–5 sessions per week',
 'Set screen time rules, model healthy tech use, encourage alternative activities',
 'Supports physical health, focus, and digital responsibility',
 '3–5 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age9_11', 'Tech Balance Badge'),

-- Physical Development & Health (Ages 12+)
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Understand Puberty and Bodily Changes',
 'Reduces confusion and anxiety about development',
 'Can explain major physical and emotional changes',
 'Have honest talks about puberty, offer trusted resources or books',
 'Builds confidence, reduces anxiety, and promotes healthy development',
 '2–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Growing Up Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Establish a Regular Exercise Routine',
 'Supports physical and mental health',
 'Engages in exercise 3–5 times per week',
 'Join sports, take walks, do fitness challenges, or try dance classes',
 'Improves fitness, mental health, and energy levels',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Fitness Star Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Practice Healthy Eating Habits',
 'Fuels the body and prevents illness',
 'Eats balanced meals most days',
 'Teach meal prep, involve them in grocery shopping, discuss food labels',
 'Encourages nutrition awareness, energy, and long-term health',
 '3–4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Healthy Eater Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Learn Personal Hygiene Independence',
 'Promotes confidence and self-respect',
 'Completes daily hygiene tasks independently',
 'Ensure consistent routines: bathing, deodorant, skincare, oral care',
 'Supports self-respect, social confidence, and overall health',
 '3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Hygiene Hero Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Understand the Importance of Sleep',
 'Affects growth, focus, and mood',
 'Maintains consistent bedtime and wake-up times',
 'Set screen-free wind-down routines and discuss sleep''s role in health',
 'Supports cognitive function, mood regulation, and growth',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Sleep Champion Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Develop Sexual Health Awareness (Age-appropriate)',
 'Empowers responsible, informed choices',
 'Demonstrates understanding of consent, safety, and respect',
 'Provide accurate info about consent, safety, and respect for others',
 'Promotes safety, healthy relationships, and self-respect',
 '4 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Responsible Teen Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Know Basic First Aid and Emergency Response',
 'Prepares for unexpected situations',
 'Can demonstrate basic first aid steps',
 'Learn CPR basics, how to use a first aid kit, or respond to common issues',
 'Increases safety awareness and confidence in emergencies',
 '4–6 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Safety Star Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Monitor and Communicate About Mental Health',
 'Connects physical and emotional well-being',
 'Regularly talks about stress, anxiety, or mood changes',
 'Normalize therapy, check in regularly, and recognize stress signs',
 'Encourages holistic wellness and early support seeking',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Mental Wellness Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Avoid Harmful Substances (Drugs, Alcohol, Vaping)',
 'Prevents risky behavior and promotes safety',
 'Abstains from harmful substances',
 'Discuss peer pressure, show real-life stories, set clear family values',
 'Protects health, promotes safety, and builds self-control',
 'Ongoing', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Health Guardian Ribbon'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440004', NULL, NULL, 'Working On', 'Balance Screen Time and Physical Activity',
 'Prevents sedentary habits and supports wellness',
 'Follows screen time limits while staying active',
 'Create limits, suggest unplugged fun, and model balance as a parent',
 'Supports fitness, mental health, and daily productivity',
 '2–3 weeks', true, true, NOW(), NOW(), false, false, 0,
 'age_12plus', 'Balanced Lifestyle Badge');