INSERT INTO goals_plan (
    id, core_value_id, user_id, child_id, status, area, goal, measurable,
    achievable, relevant, time_bound, is_default, is_active, created_at, updated_at,
    is_edited, is_selected, progress, age_group, celebration
) VALUES


-- Social Development Goals (Age 3–5)
-- 1. Manners & Greetings
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Manners & Greetings',
 'Say "please," "thank you," "excuse me," and greet others appropriately',
 'Uses polite words and greetings in 7/10 interactions',
 'Role-play, modeling, daily reminders, verbal praise during practice',
 'Builds respect, politeness, friendliness, and social confidence',
 '90–120 times in 6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 2. Sharing & Turn-Taking
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Sharing & Turn-Taking',
 'Take turns in games and share toys without conflict',
 'Completes 4/5 turns during structured play',
 'Guided practice with siblings/friends, timers, praise sharing and turn-taking',
 'Promotes fairness, patience, empathy, and cooperation',
 '12–24 times in 3 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 3. Social Rules
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Social Rules',
 'Follow simple group rules (sit, wait in line)',
 'Completes 3/4 group instructions',
 'Practice at home routines, gentle reminders, praise attempts',
 'Prepares for structured social environments',
 '16–24 times in 2 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 4. Confidence & Independence
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Confidence & Independence',
 'Say their name and age when meeting others; use words to express wants/needs',
 'Introduces self and expresses needs in 3/5 interactions',
 'Role-play, guided prompts, modeling, praise effort',
 'Builds confidence, personal identity, and communication skills',
 '40–60 times in 1 month',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 5. Boundaries
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Boundaries',
 'Respect personal space (no grabbing/touching)',
 'Demonstrates awareness 4/5 times',
 'Model, practice "personal space bubble," praise attempts',
 'Teaches boundaries and awareness',
 '16 times in 2 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 6. Empathy
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Empathy',
 'Recognize and respond to others'' emotions',
 'Responds empathetically in 3/5 scenarios',
 'Storybooks, guided reflection, role-play, praise empathetic acts',
 'Builds kindness and emotional intelligence',
 '16 times in 2 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 7. Apologizing & Conflict
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Apologizing & Conflict',
 'Say "I''m sorry" and express feelings like "That hurt my feelings"',
 'Uses phrases in 3/5 conflicts',
 'Role-play, puppets, gentle correction, praise attempts',
 'Encourages accountability and non-aggressive conflict resolution',
 '12–24 times in 3 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 8. Participation & Complimenting
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Participation & Complimenting',
 'Join group activities and say kind words ("Good job!")',
 'Participates in 4/5 group sessions and gives compliments in 3/5 interactions',
 'Enroll in group play/storytime, model behavior, praise attempts',
 'Builds belonging, listening skills, positivity, and social support',
 '12–24 times in 3 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- 9. Social Cues & Friendship
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Social Cues & Friendship',
 'Notice others'' reactions and initiate peer interactions',
 'Identifies reactions in 3/4 scenarios; initiates play in 3/5 interactions',
 'Guided reflection, role-play, model, praise attempts',
 'Builds awareness, responsiveness, and meaningful peer connections',
 '12–24 times in 3 months',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age3_5', '5 stars + certificate'),

-- Age 6-8
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Building & Maintaining Friendships',
 'Arrange playdates and discuss what makes a good friend',
 'Engages in 2–3 positive peer interactions per week',
 'Schedule playdates, talk through friendship qualities',
 'Encourages emotional connection and belonging',
 '6–8 interactions in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Empathy',
 'Ask "How do you think your friend felt when…?"',
 'Responds with empathetic statements in 3/5 situations',
 'Model reflective questioning, guide conversation',
 'Helps children respond kindly and consider others'' feelings',
 '6–8 reflections in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Respecting Differences',
 'Recognize and value differences in others',
 'Identifies differences and responds respectfully in 3/5 scenarios',
 'Read books about diverse people and cultures, discuss scenarios',
 'Fosters inclusion and global awareness',
 '6–8 discussions in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Group Participation',
 'Join clubs, group games, or sports',
 'Participates successfully in 2–3 group activities per week',
 'Encourage joining school clubs, sports, or cooperative games',
 'Builds teamwork, turn-taking, and collaboration',
 '6–8 activities in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Polite Language & Manners',
 'Use "please," "thank you," eye contact, and greetings',
 'Demonstrates polite language in 3/5 peer interactions',
 'Model, prompt, and praise polite interactions',
 'Strengthens social skills and respect',
 '12–16 interactions in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Mastered', 'Apologizing & Repairing Mistakes',
 'Say "I''m sorry" sincerely and repair mistakes',
 'Uses apology appropriately in 3/5 conflict situations',
 'Model apologies, role-play common scenarios',
 'Teaches accountability and conflict resolution',
 '6–8 situations in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Recognizing Social Cues & Boundaries',
 'Notice body language, personal space, and tone',
 'Correctly interprets cues in 3/5 interactions',
 'Practice reading expressions, model appropriate boundaries',
 'Develops awareness of social signals and boundaries',
 '6–8 observations in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Speaking Up Respectfully',
 'Express opinions clearly while being kind',
 'Shares ideas respectfully in 3/5 family or group interactions',
 'Role-play expressing opinions, guide phrasing',
 'Balances assertiveness with kindness',
 '6–8 opportunities in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Navigating Peer Pressure',
 'Say "no" kindly and confidently when pressured',
 'Refuses in 3/5 peer pressure scenarios',
 'Use role-playing and scripts to practice responses',
 'Supports confidence in personal values and choices',
 '6–8 practice scenarios in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Conflict Resolution with Guidance',
 'Use "I feel… because…" and active listening strategies',
 'Resolves minor conflicts with guidance in 3/5 instances',
 'Model language, guide practice during disputes',
 'Builds early conflict resolution skills',
 '6–8 conflicts in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Contributing to Group Tasks',
 'Complete assigned shared responsibilities',
 'Completes assigned tasks in 3/5 group activities',
 'Assign small group chores, projects, or family tasks',
 'Develops responsibility and cooperation',
 '6–8 tasks in 4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age6_8', '5 stars + certificate'),

-- Age 9-11
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Friendship Building',
 'Build and maintain friendships',
 'Resolves minor disagreements and maintains friendship in 3–4 situations',
 'Discuss qualities of a good friend, role-play handling conflicts kindly',
 'Teaches loyalty, empathy, and communication',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Friendship Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Peer Pressure Response',
 'Recognize and respond appropriately to peer pressure',
 'Makes independent choices in 3–4 role-play scenarios',
 'Role-play peer pressure situations, discuss choices and consequences',
 'Encourages confidence, integrity, and decision-making',
 '3–5 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Integrity Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Respect for Diversity',
 'Show respect for different perspectives and cultures',
 'Participates respectfully in 2–3 cross-cultural activities',
 'Learn about traditions, attend cultural events, or host discussions',
 'Fosters inclusivity, tolerance, and cultural awareness',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Cultural Awareness Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Conflict Management',
 'Manage conflict peacefully',
 'Resolves disagreements using "I" statements in 2–3 scenarios',
 'Teach active listening, problem-solving steps, and model calm negotiation',
 'Builds emotional control, communication, and problem-solving skills',
 '3–5 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Peaceful Resolver Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Boundaries & Consent',
 'Understand personal boundaries and consent',
 'Demonstrates understanding in 2–3 social situations',
 'Discuss safe vs. unsafe touch, saying no, and respecting others'' space',
 'Encourages self-respect, respect for others, and safety awareness',
 '3–4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Respect Star sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Leadership & Teamwork',
 'Develop leadership and teamwork skills',
 'Successfully leads or contributes in 2–3 group activities',
 'Encourage group projects, class roles, or club leadership opportunities',
 'Builds confidence, responsibility, and collaboration skills',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Team Leader Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Digital Etiquette',
 'Practice good digital behavior and etiquette',
 'Demonstreates respectful online behavior in 2–3 digital interactions',
 'Teach kind commenting, avoiding drama, and reporting harmful behavior',
 'Prepares for responsible, safe, and respectful online interactions',
 '3–5 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Digital Citizen Star'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Inclusion & Compassion',
 'Support and include peers who are different',
 'Acts inclusively toward 2–3 peers who are new or different',
 'Encourage inclusion of new students or children with special needs',
 'Builds empathy, compassion, and a sense of community',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Compassion Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Accountability',
 'Take responsibility for actions and mistakes',
 'Makes amends in 2–3 situations when a mistake occurs',
 'Guide reflection, discuss consequences, and model repair behaviors',
 'Builds maturity, accountability, and social responsibility',
 '3–5 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Responsible Citizen sticker'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On', 'Asking for Help',
 'Learn how to ask for help or clarification',
 'Requests guidance in 2–3 situations appropriately',
 'Practice asking teachers, parents, or peers for help when needed',
 'Encourages independence, self-advocacy, and healthy communication',
 '3–4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age9_11', 'Help-Seeker Star'),

-- Age 12+
(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Build and Maintain Friendships',
 'Develop lasting friendships through trust, communication, and shared activities',
 'Maintains 2–3 positive friendships over 8 weeks and engages in regular communication',
 'Model empathy, provide conflict-resolution strategies, schedule group activities',
 'Builds emotional support, sense of belonging, and interpersonal skills',
 '8 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Friendship Badge + small group celebration'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Navigate Peer Pressure',
 'Make independent, value-driven decisions when facing peer pressure',
 'Successfully demonstrates saying "no" or alternative choices in 3–4 scenarios',
 'Role-play scenarios, discuss strategies, praise assertive decision-making',
 'Encourages confidence, integrity, and personal boundaries',
 '6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Confidence Ribbon + personal reflection'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Respect Differences',
 'Appreciate diverse perspectives, cultures, and opinions',
 'Demonstrates inclusive behavior in school or social settings in 4/5 instances',
 'Exposure to diverse groups, discussion of cultural norms, inclusive projects',
 'Fosters inclusivity, empathy, and social awareness',
 '6–8 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Diversity Champion Badge'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Manage Conflicts',
 'Resolve conflicts respectfully using negotiation and active listening',
 'Resolves 3 conflicts using "I" statements or active listening in 4–5 situations',
 'Teach mediation skills, model dialogue, practice role-play conflict scenarios',
 'Strengthens problem-solving, maturity, and interpersonal skills',
 '6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Peace-Maker Badge + certificate of recognition'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Assertive Communication',
 'Express opinions, feelings, and needs respectfully',
 'Successfully communicates in 3–5 group or one-on-one settings without aggression',
 'Practice "I feel… because…" statements, model assertive yet polite responses',
 'Promotes self-advocacy, confidence, and healthy relationships',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Assertiveness Star + recognition in family/class'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Teamwork and Collaboration',
 'Contribute effectively to group tasks and projects',
 'Completes 2–3 team tasks successfully while supporting peers',
 'Group projects, collaborative games, discussion of roles and responsibilities',
 'Builds cooperation, leadership, and social responsibility',
 '6–8 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Teamwork Badge + small group reward'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Digital Etiquette',
 'Interact safely and respectfully online',
 'Demonstrates appropriate digital behavior in 5/5 online interactions',
 'Teach online norms, set boundaries, model respectful responses',
 'Encourages responsible online behavior and protects reputation',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Digital Respect Certificate'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Support Peers',
 'Help peers in need emotionally, academically, or socially',
 'Offers help to peers in 3–5 situations and shows empathy',
 'Encourage mentorship, model supportive behavior, recognize acts of kindness',
 'Strengthens empathy, leadership, and community-building',
 '6–8 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Helping Hand Badge + public recognition'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Responsibility for Actions',
 'Own up to mistakes and learn from them',
 'Demonstrates accountability in 3–4 real-life scenarios',
 'Role-play situations, discuss consequences, praise reflection',
 'Builds maturity, ethics, and social credibility',
 '4–6 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Accountability Ribbon + personal reflection'),

(uuid_generate_v4(), '550e8400-e29b-41d4-a716-446655440000', NULL, NULL,
 'Working On',
 'Ask for Help Effectively',
 'Request clarification or support when needed',
 'Successfully asks for help in 3–5 learning or social contexts',
 'Teach phrasing strategies, model respectful requests, encourage independence',
 'Promotes independence, problem-solving, and confidence',
 '4 weeks',
 TRUE, TRUE, NOW(), NOW(), FALSE, FALSE, 0, 'age_12plus', 'Help-Seeker Star + recognition');